// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6OvAUPFNCkZRSMgw48EIODy6HN_-FIYY',
    appId: '1:166882859375:web:7cc716e3dc7f253e32309a',
    messagingSenderId: '166882859375',
    projectId: 'drawing-app-firebase',
    authDomain: 'drawing-app-firebase.firebaseapp.com',
    storageBucket: 'drawing-app-firebase.firebasestorage.app',
    measurementId: 'G-P07VQLCWGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpjPu7-l-6J2Gv0SLuJhrMTm2fTJ4mB8s',
    appId: '1:166882859375:android:ce87b57d50c4bd8e32309a',
    messagingSenderId: '166882859375',
    projectId: 'drawing-app-firebase',
    storageBucket: 'drawing-app-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4AhgoTMaLuz-SGiYjJlZJ7VjHecrfKkQ',
    appId: '1:166882859375:ios:feb24bf68e8c109132309a',
    messagingSenderId: '166882859375',
    projectId: 'drawing-app-firebase',
    storageBucket: 'drawing-app-firebase.firebasestorage.app',
    iosBundleId: 'com.example.paintingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4AhgoTMaLuz-SGiYjJlZJ7VjHecrfKkQ',
    appId: '1:166882859375:ios:feb24bf68e8c109132309a',
    messagingSenderId: '166882859375',
    projectId: 'drawing-app-firebase',
    storageBucket: 'drawing-app-firebase.firebasestorage.app',
    iosBundleId: 'com.example.paintingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6OvAUPFNCkZRSMgw48EIODy6HN_-FIYY',
    appId: '1:166882859375:web:a60e584d749eb62d32309a',
    messagingSenderId: '166882859375',
    projectId: 'drawing-app-firebase',
    authDomain: 'drawing-app-firebase.firebaseapp.com',
    storageBucket: 'drawing-app-firebase.firebasestorage.app',
    measurementId: 'G-XTNTW8WER7',
  );
}
